# Generated by Django 5.1.2 on 2024-11-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://img.freepik.com/premium-vector/loading-icon_167801-436.jpg?w=360', max_length=5000),
        ),
    ]
